import { createEnv } from "@t3-oss/env-nextjs"
import { z } from "zod"

export const env = createEnv({
    server: {
        DATABASE_URL: z.string().url(),
        DIRECT_URL: z.string().url(),
        NODE_ENV: z.enum(["development", "test", "production"]).default("development"),
        CLERK_SECRET_KEY: z.string(),
        UPLOADTHING_TOKEN: z.string(),
        STRIPE_SECRET_KEY: z.string(),
        URL: z.string().url(),
        SUPER_FRETE_TOKEN: z.string(),
        SUPER_FRETE_URL: z.string().url(),
        APP_USER_AGENT: z.string(),
        COMPANY_NAME_FOR_ADDRESS: z.string(),
        COMPANY_CEP: z.string(),
        COMPANY_STATE: z.string(),
        COMPANY_CITY: z.string(),
        COMPANY_NEIGHBORHOOD: z.string(),
        COMPANY_STREET: z.string(),
        APP_NAME: z.string(),
        APP_SUPPORT_EMAIL: z.string().email(),
        CRON_SECRET: z.string(),
    },
    client: {
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: z.string(),
        NEXT_PUBLIC_CLERK_SIGN_IN_URL: z.string(),
        NEXT_PUBLIC_CLERK_SIGN_UP_URL: z.string(),
        NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: z.string(),
        NEXT_PUBLIC_APP_NAME: z.string(),
        NEXT_PUBLIC_BRASIL_API: z.string().url(),
    },
    runtimeEnv: {
        DATABASE_URL: process.env.DATABASE_URL,
        DIRECT_URL: process.env.DIRECT_URL,
        NODE_ENV: process.env.NODE_ENV,
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY,
        CLERK_SECRET_KEY: process.env.CLERK_SECRET_KEY,
        NEXT_PUBLIC_CLERK_SIGN_IN_URL: process.env.NEXT_PUBLIC_CLERK_SIGN_IN_URL,
        NEXT_PUBLIC_CLERK_SIGN_UP_URL: process.env.NEXT_PUBLIC_CLERK_SIGN_UP_URL,
        UPLOADTHING_TOKEN: process.env.UPLOADTHING_TOKEN,
        NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY,
        STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
        URL: process.env.URL,
        SUPER_FRETE_TOKEN: process.env.SUPER_FRETE_TOKEN,
        SUPER_FRETE_URL: process.env.SUPER_FRETE_URL,
        APP_USER_AGENT: process.env.APP_USER_AGENT,
        APP_NAME: process.env.APP_NAME,
        NEXT_PUBLIC_APP_NAME: process.env.NEXT_PUBLIC_APP_NAME,
        COMPANY_NAME_FOR_ADDRESS: process.env.COMPANY_NAME_FOR_ADDRESS,
        COMPANY_CEP: process.env.COMPANY_CEP,
        COMPANY_STATE: process.env.COMPANY_STATE,
        COMPANY_CITY: process.env.COMPANY_CITY,
        COMPANY_NEIGHBORHOOD: process.env.COMPANY_NEIGHBORHOOD,
        COMPANY_STREET: process.env.COMPANY_STREET,
        APP_SUPPORT_EMAIL: process.env.APP_SUPPORT_EMAIL,
        NEXT_PUBLIC_BRASIL_API: process.env.NEXT_PUBLIC_BRASIL_API,
        CRON_SECRET: process.env.CRON_SECRET,
    },
    skipValidation: !!process.env.SKIP_ENV_VALIDATION,
    emptyStringAsUndefined: true,
})
